import json
from typing import Dict
from utils.llm import generate_content

PITCHDECK_SYSTEM_PROMPT = """
You are an expert in MSME and startup finance.
You create concise, investor-ready pitchdeck outlines for very small businesses.

You will receive STRICT JSON with business financial metrics and context.
You must respond with STRICT JSON in the following schema:

{
  "title": string,           // main deck title
  "subtitle": string,        // optional, can be empty
  "slides": [
    {
      "title": string,
      "bullets": [string, ...]   // 3-6 bullet points, short and concrete
    },
    ...
  ]
}

Guidelines:
- Keep language simple, suited for Indian micro-entrepreneurs applying for loans / small investors.
- Focus on: business overview, revenue trends, cashflow health, key customers, risks and opportunities.
- DO NOT invent crazy metrics: only use or derive from provided numbers.
- If some data is missing, be honest ("Data not available") instead of guessing.
- Return ONLY JSON, no commentary.
"""

def generate_pitchdeck_outline(metrics: Dict) -> Dict:
    """
    Generates a pitch deck outline.
    """
    content = json.dumps(metrics, indent=2)
    result = generate_content(PITCHDECK_SYSTEM_PROMPT, content)
    
    # Fallback structure if error
    if not result or "error" in result:
        print(f"Pitchdeck Agent Error: {result.get('error', 'Unknown')}. Using Mock Data.")
        return {
            "title": f"{metrics.get('business_name', 'Business')} – Growth Strategy",
            "subtitle": "Investor Presentation (Generated by Verity)",
            "slides": [
                {
                    "title": "Executive Summary",
                    "bullets": [
                        f"Established {metrics.get('industry', 'Business')} in {metrics.get('location', 'India')}.",
                        "Consistent revenue growth over the last quarter.",
                        "Seeking investment to expand operations and inventory."
                    ]
                },
                {
                    "title": "Financial Highlights",
                    "bullets": [
                        f"Total Inflow (Last 3M): ₹{metrics.get('total_inflow_last_3m', 0):,.2f}",
                        f"Revenue Growth: {metrics.get('revenue_growth_percent', 0):.1f}% MoM",
                        "Healthy cashflow management with controlled expenses."
                    ]
                },
                {
                    "title": "Market Opportunity",
                    "bullets": [
                        "Growing demand in the local market.",
                        "Opportunity to capture 15% more market share.",
                        "Low competition in the immediate vicinity."
                    ]
                },
                {
                    "title": "Ask & Use of Funds",
                    "bullets": [
                        "Seeking ₹5,00,000 for working capital.",
                        "Funds will be used for inventory and marketing.",
                        "Projected ROI of 20% within 12 months."
                    ]
                }
            ]
        }
    return result
