import json
from typing import Dict
from utils.llm import generate_content

PITCHDECK_SYSTEM_PROMPT = """
You are an expert in MSME and startup finance.
You create concise, investor-ready pitchdeck outlines for very small businesses.

You will receive STRICT JSON with business financial metrics and context.
You must respond with STRICT JSON in the following schema:

{
  "title": string,           // main deck title
  "subtitle": string,        // optional, can be empty
  "slides": [
    {
      "title": string,
      "bullets": [string, ...]   // 3-6 bullet points, short and concrete
    },
    ...
  ]
}

Guidelines:
- Keep language simple, suited for Indian micro-entrepreneurs applying for loans / small investors.
- Focus on: business overview, revenue trends, cashflow health, key customers, risks and opportunities.
- DO NOT invent crazy metrics: only use or derive from provided numbers.
- If some data is missing, be honest ("Data not available") instead of guessing.
- Return ONLY JSON, no commentary.
"""

def generate_pitchdeck_outline(metrics: Dict) -> Dict:
    """
    Generates a pitch deck outline.
    """
    content = json.dumps(metrics, indent=2)
    result = generate_content(PITCHDECK_SYSTEM_PROMPT, content)
    
    # Fallback structure if error
    if not result or "error" in result:
        return {
            "title": f"{metrics.get('business_name', 'Business')} – Financial Overview",
            "subtitle": "Generated by Verity (Fallback)",
            "slides": [
                {"title": "Error", "bullets": ["Failed to generate deck content."]}
            ]
        }
    return result
